apiVersion: v1
kind: Pod
metadata:
  name: host-pod
spec:
  restartPolicy: never
  securityContext:
    privileged: true
    runAsUser: 1000
    runAsGroup: 1001
  hostAliases:
    - ip: "172.16.215.105"
      hostnames:
        - "isxcode"
  volumes:
    - name: users
      hostPath:
        path: /etc/passwd
