### 提交任务
POST http://localhost:8080/yag/executeWork
Content-Type: application/json

{
  "appName": "test app",
  "mainClass": "com.isxcode.star.plugin.querysql.Execute",
  "appResourcePath": "/Users/ispong/Isxcode/spark-yun/spark-yun-plugins/spark-query-sql-plugin/build/libs/spark-query-sql-plugin-3.0.1-plain.jar",
  "pluginReq": {
    "sql": "show databases;show databases"
  },
  "sparkHomePath": "/Users/ispong/Downloads/spark-3.1.1-bin-hadoop3.2",
  "agentLibPath": "/Users/ispong/Isxcode/spark-yun/spark-yun-dist/build/lib"
}

### 查询状态
GET http://localhost:8080/yag/getStatus?applicationId=application_1680753912057_0003

### 查询日志
GET http://localhost:8080/yag/getLog?applicationId=application_1680753912057_0003

### 查询数据
GET http://localhost:8080/yag/getData?applicationId=application_1680753912057_0003

### 中止作业
GET http://localhost:8080/yag/stopJob?applicationId=application_1680753912057_0003

### 心跳检测
GET http://localhost:8080/yag/heartCheck


