spring:

  security:
    user:
      roles: ADMIN
      name: admin
      password: admin123

  jpa:
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/zhiqingyun
    username: root
    password: ispong123

  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/zhiqingyun
    user: root
    password: ispong123
    locations: classpath:db/migration/mysql
    enabled: false

  quartz:
    properties:
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://localhost:30306/zhiqingyun
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: ispong123

logging:
  level:
    root: info

spark-yun:
  resources-path: classpath:resources