server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin123

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.zhiqingyun/h2/data;AUTO_SERVER=TRUE
    username: root
    password: root123

isx-app:
  resources-path: classpath:resources
  admin-passwd: admin123

spark-yun:
  agent-retry-count: 3
  agent-retry-interval: 2000
  default-agent-port: 30177
  tmp-dir: /tmp
