spring:

  security:
    user:
      roles: ADMIN
      name: admin
      password: admin123

  jpa:
    database: h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.zhiqingyun/h2/data
    username: root
    password: root123

  flyway:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.zhiqingyun/h2/data
    user: root
    password: root123
    locations: classpath:db/migration/h2

  quartz:
    properties:
      org.quartz.dataSource.quartzDataSource.driver: org.h2.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:h2:file:~/.zhiqingyun/h2/data
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: root123

logging:
  level:
    root: info

# 需要开发者自定义路径
spark-yun:
  resources-path: \\Users\\ispong\\.zhiqingyun\\resources  # 资源文件目录
  agent-bin-dir: \\Users\\ispong\\Isxcode\\spark-yun\\spark-yun-dist\\src/main/bash # bash脚本路径
  agent-tar-gz-dir: \\Users\\ispong\\Isxcode\\spark-yun\\spark-yun-dist\\build/distributions # 代理包路径