name: Create bug
description: 创建缺陷
title: '[Bug] '
labels: ["缺陷"]
body:
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used (部署的操作系统)
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: checkboxes
    id: download_from
    attributes:
      label: Download from (安装来源)
      options:
        - label: 本地源码编译
        - label: 官网二进制
        - label: 阿里镜像仓库
        - label: Docker Hub
  - type: input
    id: branch
    attributes:
      label: Version number (当前版本号，获取方式：http://localhost:8080/tools/open/version)
      placeholder: latest
      value: latest
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Bug description (缺陷描述)
      placeholder: Pictures, videos, cUrl, text descriptions, etc.(图片、视频、cUrl、文字描述等)
    validations:
      required: false
  - type: textarea
    id: frontend
    attributes:
      label: Reproduction steps (复现步骤)
      placeholder: Pictures, videos, etc.(图片、视频等)
    validations:
      required: false
  - type: textarea
    id: backend
    attributes:
      label: cUrls and response (请求和响应)
      placeholder: 'curl http://localhost:8080/vip/form/pageForm '
    validations:
      required: false