name: Create Release Bug (For tester)
description: 创建发版缺陷，测试人员使用
labels: [ "回归缺陷" ]
body:
  - type: input
    id: releaseBranchName
    attributes:
      label: ReleaseName (发布版本号)
      placeholder: "For example, 0.9.0、0.2.0、1.9.0"
    validations:
      required: true
  - type: dropdown
    id: developer
    attributes:
      label: Scope (范围)
      options:
        - Don't Know (不清楚)
        - Frontend (前端)
        - Backend (后端)
        - Web (官网)
      default: 0
  - type: dropdown
    id: level
    attributes:
      label: Level (等级)
      options:
        - P0
        - P1
        - P2
        - P3
      default: 1
  - type: textarea
    id: describe
    attributes:
      label: Bug description (缺陷描述)
      placeholder: text descriptions (文字描述)
    validations:
      required: true
  - type: textarea
    id: frontend
    attributes:
      label: Reproduction steps (复现步骤)
      placeholder: Pictures, videos, etc.(图片、视频等)
    validations:
      required: false
  - type: textarea
    id: backend
    attributes:
      label: cUrls and response (请求和响应)
      placeholder: 'curl http://localhost:8080/vip/form/pageForm '
    validations:
      required: false
