name: Help docs
description: 官方文档补充
title: '[Docs] '
labels: ["文档"]
body:
  - type: input
    id: branch
    attributes:
      label: Branch name (分支名)
      placeholder: main
      value: main
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Docs description (缺陷描述)
      placeholder: Pictures, videos, cUrl, text descriptions, etc.(图片、视频、cUrl、文字描述等)
    validations:
      required: false