name: Consultation message
description: 咨询留言
title: '不推荐提交'
labels: ["咨询留言"]
body:
    - type: textarea
      id: link
      attributes:
        label: 将描述内容发送至【 hello@isxcode.com 】
        placeholder: '联系方式\n 咨询内容\n 预约时间'
      validations:
        required: true