name: Consultation message
description: 咨询留言
title: '电话联系: 400-8848-170'
labels: ["咨询留言"]
body:
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
