name: 创建日常任务
title: ":art: "
labels: ["日常任务"]
body:
  - type: markdown
    attributes:
      value: |
        欢迎创建一个日常任务
  - type: dropdown
    id: version
    description:
    attributes:
      label: 所属分组
      options:
        - 产品组
        - 开发组
        - 管理组
        - 测试组
    validations:
      required: true
  - type: dropdown
    id: version1
    description:
    attributes:
      label: 紧急程度
      options:
        - 超级急
        - 紧急
        - 普通
    validations:
      required: true    
  - type: textarea
    id: describe-content
    attributes:
      label: 任务描述
      placeholder: 请填写任务内容...
      description: 
      value: "标题即任务内容"
    validations:
      required: true
