name: 创建日常任务
description: 欢迎提交一个日常任务
title: ":art: "
labels: ["日常任务"]
body:
  - type: dropdown
    id: download
    attributes:
      label: 负责人
      description: "选择任务负责人"
      options:
        - 项目经理
        - 项目管理
        - 主产品经理
        - 产品经理
        - 技术负责人
        - 技术开发
        - 主测试
        - 测试员
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 日常任务内容
      description: "描述一下日常任务内容"
      placeholder: 请填写日常任务内容...
      value: 标题即是日常任务内容
    validations:
      required: true
