name: 创建需求
description: 欢迎提交一个需求
title: ":sparkles: "
labels: ["需求"]
body:
  - type: input
    id: org
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 需求内容
      description: "描述一下需求内容"
      placeholder: 请填写需求内容...
      value: |
        "标题即是需求内容"
    validations:
      required: true
