-- 系统监控改用double类型
ALTER TABLE SY_MONITOR
    MODIFY COLUMN DISK_IO_READ_SPEED DOUBLE;

ALTER TABLE SY_MONITOR
    MODIFY COLUMN DISK_IO_WRITE_SPEED DOUBLE;

ALTER TABLE SY_MONITOR
    MODIFY COLUMN NETWORK_IO_WRITE_SPEED DOUBLE;

ALTER TABLE SY_MONITOR
    MODIFY COLUMN NETWORK_IO_READ_SPEED DOUBLE;