-- 字段血缘表
CREATE TABLE SY_META_COLUMN_LINEAGE
(
    ID                      VARCHAR(200) NOT NULL COMMENT '字段血缘id',
    FROM_DB_ID              VARCHAR(200) NOT NULL COMMENT '来源数据源',
    FROM_TABLE_NAME         VARCHAR(200) NOT NULL COMMENT '来源表名',
    FROM_COLUMN_NAME        VARCHAR(200) NOT NULL COMMENT '来源字段名',
    WORK_ID                 VARCHAR(200) NOT NULL COMMENT '作业',
    WORK_VERSION_ID         VARCHAR(200) NOT NULL COMMENT '作业版本',
    TO_DB_ID                VARCHAR(200) NOT NULL COMMENT '去向数据源',
    TO_TABLE_NAME           VARCHAR(200) NOT NULL COMMENT '去向表名',
    TO_COLUMN_NAME          VARCHAR(200) NOT NULL COMMENT '去向字段名',
    REMARK                  VARCHAR(500) COMMENT '血缘备注',
    VERSION_NUMBER          INT          NOT NULL COMMENT '版本号',
    CREATE_BY               VARCHAR(200) NOT NULL COMMENT '创建人',
    CREATE_DATE_TIME        TIMESTAMP    NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_BY        VARCHAR(200) NOT NULL COMMENT '更新人',
    LAST_MODIFIED_DATE_TIME TIMESTAMP    NOT NULL COMMENT '更新时间',
    DELETED                 INT          NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    TENANT_ID               VARCHAR(200) NOT NULL COMMENT '租户id',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SY_META_COLUMN_LINEAGE_ID (ID)
) COMMENT = '字段血缘表';