-- 依赖包表
CREATE TABLE SY_LIB_PACKAGE (
    ID VARCHAR(200) NOT NULL PRIMARY KEY COMMENT '依赖包id',
    NAME VARCHAR(200) NOT NULL COMMENT '依赖包名称',
    FILE_ID_LIST VARCHAR(5000) COMMENT '依赖包中依赖',
    REMARK VARCHAR(500) COMMENT '依赖包备注',
    VERSION_NUMBER INT NOT NULL COMMENT '版本号',
    CREATE_BY VARCHAR(200) NOT NULL COMMENT '创建人',
    CREATE_DATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_BY VARCHAR(200) NOT NULL COMMENT '更新人',
    LAST_MODIFIED_DATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    DELETED INT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    TENANT_ID VARCHAR(200) NOT NULL COMMENT '租户id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 新增任务包配置字段
ALTER TABLE SY_WORK_CONFIG
    ADD COLUMN LIB_PACKAGE_CONFIG LONGTEXT COMMENT '任务包配置';

-- 版本表中添加任务包配置字段
ALTER TABLE SY_WORK_VERSION
    ADD COLUMN LIB_PACKAGE_CONFIG LONGTEXT COMMENT '任务包配置';