-- API黑白名单配置表
CREATE TABLE SY_API_ACCESS_RULE
(
    ID                      VARCHAR(200)  NOT NULL PRIMARY KEY UNIQUE COMMENT '黑白名单id',
    NAME                    VARCHAR(200)  NOT NULL COMMENT '规则名称',
    RULE_TYPE               VARCHAR(200)  NOT NULL COMMENT '规则类型: WHITELIST/BLACKLIST',
    IP_ADDRESS              VARCHAR(2000) NOT NULL COMMENT 'IP地址，多个用换行分隔，支持正则',
    REMARK                  VARCHAR(500)  COMMENT '备注',
    VERSION_NUMBER          INT           NOT NULL COMMENT '版本号',
    CREATE_BY               VARCHAR(200)  NOT NULL COMMENT '创建人',
    CREATE_DATE_TIME        DATETIME      NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_BY        VARCHAR(200)  NOT NULL COMMENT '更新人',
    LAST_MODIFIED_DATE_TIME DATETIME      NOT NULL COMMENT '更新时间',
    DELETED                 INT DEFAULT 0 NOT NULL COMMENT '逻辑删除',
    TENANT_ID               VARCHAR(200)  NOT NULL COMMENT '租户id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API黑白名单配置表';

-- API表添加黑白名单关联字段
ALTER TABLE SY_API
    ADD COLUMN ACCESS_RULE_ID VARCHAR(200) COMMENT '黑白名单配置id';
