-- 新增Flink数据同步配置字段
ALTER TABLE SY_WORK_CONFIG
    ADD COLUMN SYNC_FLINK_CONFIG LONGTEXT;

-- 版本表中添加新增Flink数据同步配置字段
ALTER TABLE SY_WORK_VERSION
    ADD COLUMN SYNC_FLINK_CONFIG LONGTEXT;

-- doris数据源特有字段feNodes
ALTER TABLE SY_DATASOURCE
    ADD COLUMN FE_NODES VARCHAR(200);
