-- 改表名大写
RENAME TABLE sy_data_model TO SY_DATA_MODEL;
RENAME TABLE sy_column_format TO SY_COLUMN_FORMAT;
RENAME TABLE sy_data_layer TO SY_DATA_LAYER;
RENAME TABLE sy_data_model_column TO SY_DATA_MODEL_COLUMN;

-- 扩大数据模型字段
ALTER TABLE SY_DATA_MODEL
    MODIFY COLUMN BUILD_LOG LONGTEXT;

ALTER TABLE SY_DATA_MODEL
    MODIFY COLUMN TABLE_CONFIG LONGTEXT;