env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: [ ]
parserOptions:
  project:
    - tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-misused-promises": off
  "@typescript-eslint/no-floating-promises": off
  "@typescript-eslint/restrict-plus-operands": off
  "@typescript-eslint/strict-boolean-expressions": off
  "@typescript-eslint/space-before-function-paren": off
  "@typescript-eslint/indent": off
  "@typescript-eslint/consistent-type-imports": off
settings:
  react:
    version: 18.2.0
