printWidth: 120 # 每行最大长度120
tabWidth: 2 # 一个tab长度为2
useTabs: false # 不使用tab键
semi: false # 结尾取消分号
singleQuote: true # 使用单引号
quoteProps: 'as-needed'
trailingComma: 'none' # es5会自动在对象后面加,
bracketSpacing: true # 花括号前后加空格
bracketSameLine: true # > 字符不换行
arrowParens: "always" # 函数自动加括号
parser: "typescript"
endOfLine: "lf"
