spring:

  # 配置h2\swagger\druid的web登录账号密码
  security:
    user:
      roles: ADMIN
      name: admin
      password: admin123

  # 使用mysql数据库
  jpa:
    database: mysql

  # 配置至轻云业务数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiqingyun
    username: root
    password: ispong123

  # 配置flyway访问数据库信息
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiqingyun
    user: root
    password: ispong123
    locations: classpath:db/migration/mysql

  # 配置quartz自定时数据库信息
  quartz:
    properties:
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://localhost:3306/zhiqingyun
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: ispong123

# 配置至轻云
spark-yun:
  aes-slat: spark-yun # 对成加密的slat
  expiration-min: 1440 # token过期时间
  jwt-key: spark-yun # jwt加密的slat
  default-agent-port: 30177 # 默认代理端口号

# 配置日志级别
logging:
  level:
    root: info