-- standalone集群节点支持安装flink-local组件
ALTER TABLE SY_CLUSTER_NODE
  ADD COLUMN INSTALL_FLINK_LOCAL BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN SY_CLUSTER_NODE.INSTALL_FLINK_LOCAL IS '是否安装spark-local组件';

ALTER TABLE SY_CLUSTER_NODE
  ADD COLUMN FLINK_HOME_PATH varchar(200) null;
COMMENT ON COLUMN SY_CLUSTER_NODE.FLINK_HOME_PATH IS 'standalone模式flink的安装目录';