-- 字段血缘表
CREATE TABLE SY_META_COLUMN_LINEAGE
(
    ID                      VARCHAR(200) NOT NULL,
    FROM_DB_ID              VARCHAR(200) NOT NULL,
    FROM_TABLE_NAME         VARCHAR(200) NOT NULL,
    FROM_COLUMN_NAME        VARCHAR(200) NOT NULL,
    WORK_ID                 VARCHAR(200) NOT NULL,
    WORK_VERSION_ID         VARCHAR(200) NOT NULL,
    TO_DB_ID                VARCHAR(200) NOT NULL,
    TO_TABLE_NAME           VARCHAR(200) NOT NULL,
    TO_COLUMN_NAME          VARCHAR(200) NOT NULL,
    REMARK                  VARCHAR(500),
    VERSION_NUMBER          INTEGER      NOT NULL,
    CREATE_BY               VARCHAR(200) NOT NULL,
    CREATE_DATE_TIME        TIMESTAMP    NOT NULL,
    LAST_MODIFIED_BY        VARCHAR(200) NOT NULL,
    LAST_MODIFIED_DATE_TIME TIMESTAMP    NOT NULL,
    DELETED                 INTEGER      NOT NULL DEFAULT 0,
    TENANT_ID               VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_SY_META_COLUMN_LINEAGE_ID UNIQUE (ID)
);

-- 添加表注释
COMMENT ON TABLE SY_META_COLUMN_LINEAGE IS '字段血缘表';

-- 添加列注释
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.ID IS '字段血缘id';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.FROM_DB_ID IS '来源数据源';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.FROM_TABLE_NAME IS '来源表名';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.FROM_COLUMN_NAME IS '来源字段名';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.WORK_ID IS '作业';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.WORK_VERSION_ID IS '作业版本';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.TO_DB_ID IS '去向数据源';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.TO_TABLE_NAME IS '去向表名';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.TO_COLUMN_NAME IS '去向字段名';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.REMARK IS '血缘备注';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.VERSION_NUMBER IS '版本号';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.CREATE_DATE_TIME IS '创建时间';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.LAST_MODIFIED_BY IS '更新人';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.LAST_MODIFIED_DATE_TIME IS '更新时间';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.DELETED IS '逻辑删除';
COMMENT ON COLUMN SY_META_COLUMN_LINEAGE.TENANT_ID IS '租户id';