-- 依赖包表
CREATE TABLE SY_LIB_PACKAGE (
    ID                      VARCHAR(200) NOT NULL PRIMARY KEY,
    NAME                    VARCHAR(200) NOT NULL,
    FILE_ID_LIST            VARCHAR(5000),
    REMARK                  VARCHAR(500),
    VERSION_NUMBER          INTEGER NOT NULL,
    CREATE_BY               VARCHAR(200) NOT NULL,
    CREATE_DATE_TIME        TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY        VARCHAR(200) NOT NULL,
    LAST_MODIFIED_DATE_TIME TIMESTAMP NOT NULL,
    DELETED                 INTEGER NOT NULL DEFAULT 0,
    TENANT_ID               VARCHAR(200) NOT NULL
);

-- 添加列注释
COMMENT ON COLUMN SY_LIB_PACKAGE.ID IS '依赖包id';
COMMENT ON COLUMN SY_LIB_PACKAGE.NAME IS '依赖包名称';
COMMENT ON COLUMN SY_LIB_PACKAGE.FILE_ID_LIST IS '依赖包中依赖';
COMMENT ON COLUMN SY_LIB_PACKAGE.REMARK IS '依赖包备注';
COMMENT ON COLUMN SY_LIB_PACKAGE.VERSION_NUMBER IS '版本号';
COMMENT ON COLUMN SY_LIB_PACKAGE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SY_LIB_PACKAGE.CREATE_DATE_TIME IS '创建时间';
COMMENT ON COLUMN SY_LIB_PACKAGE.LAST_MODIFIED_BY IS '更新人';
COMMENT ON COLUMN SY_LIB_PACKAGE.LAST_MODIFIED_DATE_TIME IS '更新时间';
COMMENT ON COLUMN SY_LIB_PACKAGE.DELETED IS '逻辑删除';
COMMENT ON COLUMN SY_LIB_PACKAGE.TENANT_ID IS '租户id';

-- 新增任务包配置字段
ALTER TABLE SY_WORK_CONFIG
    ADD COLUMN LIB_PACKAGE_CONFIG TEXT;

-- 为新字段添加注释
COMMENT ON COLUMN SY_WORK_CONFIG.LIB_PACKAGE_CONFIG IS '任务包配置';

-- 版本表中添加任务包配置字段
ALTER TABLE SY_WORK_VERSION
    ADD COLUMN LIB_PACKAGE_CONFIG TEXT;

-- 为新字段添加注释
COMMENT ON COLUMN SY_WORK_VERSION.LIB_PACKAGE_CONFIG IS '任务包配置';