-- API黑白名单配置表
CREATE TABLE SY_API_ACCESS_RULE
(
    ID                      VARCHAR(200)  NOT NULL,
    NAME                    VARCHAR(200)  NOT NULL,
    RULE_TYPE               VARCHAR(200)  NOT NULL,
    IP_ADDRESS              VARCHAR(2000) NOT NULL,
    REMARK                  VARCHAR(500),
    VERSION_NUMBER          INTEGER       NOT NULL,
    CREATE_BY               VARCHAR(200)  NOT NULL,
    CREATE_DATE_TIME        TIMESTAMP     NOT NULL,
    LAST_MODIFIED_BY        VARCHAR(200)  NOT NULL,
    LAST_MODIFIED_DATE_TIME TIMESTAMP     NOT NULL,
    DELETED                 INTEGER       NOT NULL DEFAULT 0,
    TENANT_ID               VARCHAR(200)  NOT NULL
);

-- 添加表注释
COMMENT ON TABLE SY_API_ACCESS_RULE IS 'API黑白名单配置表';

-- 添加列注释
COMMENT ON COLUMN SY_API_ACCESS_RULE.ID IS '黑白名单id';
COMMENT ON COLUMN SY_API_ACCESS_RULE.NAME IS '规则名称';
COMMENT ON COLUMN SY_API_ACCESS_RULE.RULE_TYPE IS '规则类型: WHITELIST/BLACKLIST';
COMMENT ON COLUMN SY_API_ACCESS_RULE.IP_ADDRESS IS 'IP地址，多个用换行分隔，支持正则';
COMMENT ON COLUMN SY_API_ACCESS_RULE.REMARK IS '备注';
COMMENT ON COLUMN SY_API_ACCESS_RULE.VERSION_NUMBER IS '版本号';
COMMENT ON COLUMN SY_API_ACCESS_RULE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SY_API_ACCESS_RULE.CREATE_DATE_TIME IS '创建时间';
COMMENT ON COLUMN SY_API_ACCESS_RULE.LAST_MODIFIED_BY IS '更新人';
COMMENT ON COLUMN SY_API_ACCESS_RULE.LAST_MODIFIED_DATE_TIME IS '更新时间';
COMMENT ON COLUMN SY_API_ACCESS_RULE.DELETED IS '逻辑删除';
COMMENT ON COLUMN SY_API_ACCESS_RULE.TENANT_ID IS '租户id';

-- API表添加黑白名单关联字段
ALTER TABLE SY_API
    ADD COLUMN ACCESS_RULE_ID VARCHAR(200);
COMMENT ON COLUMN SY_API.ACCESS_RULE_ID IS '黑白名单配置id';
