server:
  port: 8080

spring:

  # 配置h2\swagger\druid的web登录账号密码
  security:
    user:
      roles: ADMIN
      name: admin
      password: admin123

  # 使用mysql数据库
  jpa:
    database: h2

  # 配置至轻云业务数据库信息
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.zhiqingyun/h2/data
    username: root
    password: root123

  # 配置flyway访问数据库信息
  flyway:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.zhiqingyun/h2/data
    user: root
    password: root123
    locations: classpath:db/migration/h2

  # 配置quartz自定时数据库信息
  quartz:
    properties:
      org.quartz.dataSource.quartzDataSource.driver: org.h2.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:h2:file:~/.zhiqingyun/h2/data
      org.quartz.dataSource.quartzDataSource.user: root
      org.quartz.dataSource.quartzDataSource.password: root123

# 配置至轻云
spark-yun:
  aes-slat: spark-yun # 对成加密的slat
  expiration-min: 1440 # token过期时间
  jwt-key: spark-yun # jwt加密的slat
  default-agent-port: 30177 # 默认代理端口号

# 配置日志级别
logging:
  level:
    root: info