name: push to ali

on:
  workflow_dispatch:
    inputs:
      admin_github_token:
        description: '管理员github token'
        required: true
        type: string
      version_number:
        description: '版本号，默认latest'
        required: true
        type: string
        default: latest

env:
  ADMIN_GITHUB_TOKEN: ${{ inputs.admin_github_token }}

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'

    steps:

      - name: Checkout spark-yun-vip
        uses: actions/checkout@v4
        with:
          token: ${{ env.ADMIN_GITHUB_TOKEN }}
          repository: "isxcode/spark-yun-vip"
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ispong
          password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}

      - name: Pull docker images
        run: |
          docker pull --platform=linux/amd64 isxcode/zhiqingyun
          docker tag isxcode/zhiqingyun registry.cn-shanghai.aliyuncs.com/isxcode/zhiqingyun:latest-amd64
          docker push registry.cn-shanghai.aliyuncs.com/isxcode/zhiqingyun:latest-amd64
          docker rmi isxcode/zhiqingyun
          docker pull --platform=linux/arm64 isxcode/zhiqingyun
          docker tag isxcode/zhiqingyun registry.cn-shanghai.aliyuncs.com/isxcode/zhiqingyun:latest-arm64
          docker push registry.cn-shanghai.aliyuncs.com/isxcode/zhiqingyun:latest-arm64
